:dizzy:
c: finally got a map of the products working in dev; but it's still throwing weird type error on products.records "Type error: Property 'records' does not exist on type '{ id: string; createdTime: string; fields: Fields; }[]'." :shit:

^^^ solved :sob: fucked the typing, had to nest - was clash b.w return from api & type :blowfish: